trigger:
- main

variables:
  pythonVersion: '3.11'
  artifactName: 'package'

  azureServiceConnection: '<YOUR_AZURE_SERVICE_CONNECTION>'
  resourceGroupName: 'rg-func-runfrompkg'
  functionAppName: 'func-runfrompkg-demo'

pool:
  vmImage: 'windows-latest'
  # 私网场景请改成你们的 self-hosted windows agent pool
  # name: 'pool-vnet-windows'

stages:
- stage: Build
  displayName: Build Zip
  jobs:
  - job: BuildZip
    displayName: Build zip package
    steps:
    - checkout: self

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(pythonVersion)'

    - powershell: |
        $ErrorActionPreference = "Stop"

        python -m pip install --upgrade pip

        # 安装依赖到 Functions Python 约定目录
        if (Test-Path "requirements.txt") {
          pip install -r requirements.txt --target ".python_packages\lib\site-packages"
        }

        $zipName = "func-$(Build.BuildId).zip"
        if (Test-Path $zipName) { Remove-Item $zipName -Force }

        # 打包（排除常见无关目录）
        $exclude = @(".git", ".venv", "__pycache__", ".pytest_cache")
        $items = Get-ChildItem -Force | Where-Object { $exclude -notcontains $_.Name }

        Compress-Archive -Path $items.FullName -DestinationPath $zipName -Force

        New-Item -ItemType Directory -Force -Path "$(Build.ArtifactStagingDirectory)" | Out-Null
        Move-Item $zipName "$(Build.ArtifactStagingDirectory)\$zipName" -Force
      displayName: "Install deps & create zip"

    - publish: $(Build.ArtifactStagingDirectory)
      artifact: $(artifactName)

- stage: Deploy
  displayName: Deploy via SCM zipdeploy (Entra)
  dependsOn: Build
  jobs:
  - job: ZipDeploy
    displayName: ZipDeploy
    steps:
    - download: current
      artifact: $(artifactName)

    - task: AzureCLI@2
      displayName: "ZipDeploy with Entra access token (PowerShell)"
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: pscore
        scriptLocation: inlineScript
        inlineScript: |
          $ErrorActionPreference = "Stop"

          $zipName = "func-$(Build.BuildId).zip"
          $zipPath = "$(Pipeline.Workspace)\$(artifactName)\$zipName"

          if (!(Test-Path $zipPath)) {
            throw "Zip not found: $zipPath"
          }

          # 1) 获取 Entra access token（由 Service Connection 登录上下文提供）
          $accessToken = az account get-access-token --query accessToken -o tsv
          if ([string]::IsNullOrWhiteSpace($accessToken)) {
            throw "Failed to get access token."
          }

          $scmBase = "https://$(functionAppName).scm.azurewebsites.net"
          $zipDeployUrl = "$scmBase/api/zipdeploy?isAsync=true"
          $deployLatestUrl = "$scmBase/api/deployments/latest"
          $deployLogUrl = "$scmBase/api/deployments/latest/log"

          $headers = @{
            "Authorization" = "Bearer $accessToken"
            "Accept"        = "application/json"
          }

          Write-Host "Starting zipdeploy (token hidden)."

          # 2) 发起 zipdeploy（POST zip 文件）
          # 用 Invoke-WebRequest 的 -InFile 可等价 curl --data-binary
          $resp = Invoke-WebRequest `
            -Method Post `
            -Uri $zipDeployUrl `
            -Headers $headers `
            -ContentType "application/zip" `
            -InFile $zipPath `
            -UseBasicParsing

          Write-Host "zipdeploy status code: $($resp.StatusCode)"
          if (($resp.StatusCode -ne 200) -and ($resp.StatusCode -ne 202)) {
            throw "zipdeploy failed with http $($resp.StatusCode)"
          }

          # 3) 轮询部署状态
          Write-Host "Polling deployment status..."
          $maxAttempts = 60
          for ($i=1; $i -le $maxAttempts; $i++) {
            Start-Sleep -Seconds 10

            try {
              $latest = Invoke-RestMethod -Method Get -Uri $deployLatestUrl -Headers $headers -UseBasicParsing
            } catch {
              Write-Host "Attempt $i: failed to query deployment status: $($_.Exception.Message)"
              continue
            }

            $status = $latest.status
            $progress = $latest.progress
            $message = $latest.message

            Write-Host ("Attempt {0}/{1}: status={2}, progress={3}, message={4}" -f $i,$maxAttempts,$status,$progress,$message)

            # Kudu 常见：4=success, 3=failed，其它=进行中
            if ($status -eq 4) {
              Write-Host "Deployment succeeded."
              exit 0
            }

            if ($status -eq 3) {
              Write-Host "Deployment failed. Fetching latest logs..."
              try {
                $logs = Invoke-RestMethod -Method Get -Uri $deployLogUrl -Headers $headers -UseBasicParsing
                $logs | ConvertTo-Json -Depth 50 | Write-Host
              } catch {
                Write-Host "Failed to fetch logs: $($_.Exception.Message)"
              }
              throw "Deployment failed."
            }
          }

          throw "Deployment polling timed out."
