apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-yaml
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.21 # 我们指定一个具体的版本
        ports:
        - containerPort: 80